### ISSUE TITLE
战斗结算页面持续错误识别为Scene: 9998: 场景跳转时的等待界面

### ISSUE THREAD

**Issue by YuiTH** [Konano/arknights-mower#42]
![image](https://user-images.githubusercontent.com/22416062/147782108-ed8e9921-653f-44e3-b351-9a117d7bd171.png)
Ctrl+C后，位置如下：
> Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/c/Users/Yui/Developer/arknights-mower/arknights_mower/__main__.py", line 273, in <module>
    main()
  File "/mnt/c/Users/Yui/Developer/arknights-mower/arknights_mower/__main__.py", line 265, in main
    target_cmd(args[1:])
  File "/mnt/c/Users/Yui/Developer/arknights-mower/arknights_mower/__main__.py", line 169, in operation
    OpeSolver().run(times, potion, originite, level, plan, eliminate)
  File "/mnt/c/Users/Yui/Developer/arknights-mower/arknights_mower/solvers/operation.py", line 197, in run
    self.sleep(3)
  File "/mnt/c/Users/Yui/Developer/arknights-mower/arknights_mower/utils/solver.py", line 41, in sleep
    time.sleep(interval)
KeyboardInterrupt

由于9998其实就是纯黑页面，怀疑adb没有正确返回截图导致该问题。但是：
1. Ctrl+C重启任务后该问题消失
2. Nox模拟器截图功能正常（不确定是不是用的adb）

所以原因还需要进一步探索。

**Comment by YuiTH** [comment]
刚才发现直接把战斗完成的界面点掉也能继续正常运行。有什么可能的方法让我查查原因吗

**Comment by Konano** [comment]
@YuiTH 是指复现不了 9998 的情况吗？

**Comment by YuiTH** [comment]
> @YuiTH 是指复现不了 9998 的情况吗？

意思是出现截图中错误将战斗结束画面识别为9998的情况后，直接点屏幕结束战斗结算，回到选择关卡界面即恢复正常。
